LogBook/Controllers/LogBookController.cs
using LogBook.Data;
using LogBook.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace LogBook.Controllers
{
    public class LogBookController : Controller
    {
        private readonly AppDb db;

        public LogBookController(AppDb db)
        {
            this.db = db;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            //var items = db.vw_PatientDivisionVisitsSummary.ToList();
            //return View(items);

            return View();
        }
        public IActionResult Search(string text)
        {
            var q = from item in db.vw_PatientDivisionVisitsSummary
                    where item.HN.Contains(text) || item.FirstName.Contains(text)
                    select item;

            //return Json(q.ToList());
            return PartialView(q.ToList());
        }

        [Route("LogBook/{an}/WardPre/Create")]
        public IActionResult Create_WardPre(string an)
        {
            ViewBag.AN = an;
            return View();
        }

        [HttpGet("LogBook/{an}/WardPre")]
        public IActionResult Details_WardPre(string an)
        {
            var q1 = (from dv in db.WardPreDivisionVisits // .DivisionVisits.OfType<WardPreDivisionVisit>()
                      where dv.VisitAN == an
                      select dv).SingleOrDefault();

            if (q1 == null)
            {
                // TODO: Send custom error message
                return RedirectToAction(nameof(HomeController.Error), nameof(HomeController));
            }

            ViewBag.AN = an;
            return View(q1);
        }

        [HttpPost("LogBook/{an}/WardPre/Create")]
        public IActionResult Create_WardPre(string an,
                                        WardPreDivisionVisit item)
        {
            var visit = db.Visits.Find(an);

            ModelState.Remove(nameof(DivisionVisit.UserName));
            ModelState.Remove(nameof(DivisionVisit.Visit));
            item.UserName = User.Identity.Name ?? "N/A";
            item.Visit = visit;
            item.CreateDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                visit.DivisionVisits.Add(item);
                db.SaveChanges();

                return RedirectToAction(nameof(Details_WardPre),new { an});
            }

            return View(item);
        }


        [Route("LogBook/{an}/Opd/Create")]
        public IActionResult Create_Opd(string an)
        {
            return View();
        }
        public IActionResult VisitRecord(string id)
        {
            var item = db.vw_PatientDivisionVisitsSummary
              .Where(x => x.AN == id).SingleOrDefault();

            if (item == null) return Content("");
            return PartialView(item);
        }
    }
}

LogBook/Views/LogBook/Create_Opd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LogBook/Views/LogBook/Create_WardPre.cshtml
@model WardPreDivisionVisit

@{
    ViewData["Title"] = "Create_WardPre";
}

<h1>Ward Pre</h1>
<div id="header">
</div>


<div asp-validation-summary="All"></div>
<form asp-action="Create_WardPre" method="post">
    <div class="form-group">
        <label>Division Name</label>
        <input asp-for="DivisionName" class="form-control" />
        <div class="text-danger">
            <span asp-validation-for="DivisionName"></span>
        </div>
    </div>

    <div class="form-group">
        <label>Ward Name</label>
        <input asp-for="WardName" class="form-control" />
        <div class="text-danger">
            <span asp-validation-for="WardName"></span>
        </div>
    </div>

    <div class="form-group">
        <label>Time Ward Arrive</label>
        <input asp-for="TimeWardArrive" class="form-control" />
        <div class="text-danger">
            <span asp-validation-for="TimeWardArrive"></span>
        </div>
    </div>

    <div class="form-group">
        <label>Diagnosis</label>
        <textarea asp-for="Diagnosis" class="form-control">
    </textarea>
        <div class="text-danger">
            <span asp-validation-for="Diagnosis"></span>
        </div>
    </div>


    <div>
        <button type="submit" class="btn btn-primary">
            Add
        </button>
    </div>
</form>

@section Scripts {
    <script>
    let url = '/logbook/visitrecord/'+ @ViewBag.AN;

    $("#header").load(url);
    </script>
}

LogBook/Views/LogBook/Details_WardPre.cshtml
@model LogBook.Models.WardPreDivisionVisit

@{
    ViewData["Title"] = "Details_WardPre";
}


<div id="header">
</div>

<h1>WardPre</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WardName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WardName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TimeWardArrive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TimeWardArrive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Diagnosis)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Diagnosis)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DivisionName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DivisionName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VisitAN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VisitAN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    <script>
    let url = '/logbook/visitrecord/'
      + @ViewBag.AN;

    $("#header").load(url);
    </script>
}

LogBook/Views/LogBook/Index.cshtml
@model IEnumerable<LogBook.Models.Queries.PatientDivisionVisitsSummary>

@{
    ViewData["Title"] = "Index";
}

<h1>Log Books</h1>

<input class="form-control my-5" />

LogBook/Views/LogBook/Search.cshtml
@model IEnumerable<PatientDivisionVisitsSummary>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HN)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.Birthdate)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.Sex)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AN)
                </th>

                <th class="text-center">
                    @Html.DisplayNameFor(model => model.WardPre)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Opd)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var classWardPre = item.WardPre > 0 ? "btn-outline-warning" : "btn-light";
                var classOpd = item.Opd > 0 ? "btn-outline-info" : "btn-light";
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => item.Birthdate)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => item.Sex)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => item.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AN)
                    </td>

                    <td class="text-center">
                        @if (item.WardPre == 0)
                        {
                            <a asp-controller="LogBook"
                               asp-action="Create_WardPre"
                               asp-route-an="@item.AN"
                               class="btn @classWardPre btn-sm btn-block">
                                N/A
                            </a>

                        }
                        else
                        {
                            <a asp-controller="LogBook"
                               asp-action="Details_WardPre"
                               asp-route-an="@item.AN"
                               class="btn @classWardPre btn-sm btn-block">
                                @item.WardPre
                            </a>
                        }
                    </td>
                    <td class="text-center">
                        <a asp-controller="LogBook"
                           asp-action="Create_Opd"
                           asp-route-an="@item.AN"
                           class="btn @classOpd btn-sm btn-block">
                            @(item.Opd == 0 ? "N/A" : item.Opd.ToString())
                        </a>
                    </td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>

</div>

LogBook/Views/LogBook/VisitRecord.cshtml
@model PatientDivisionVisitsSummary

<div class="table-responsive">
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.HN)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.Birthdate)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.Sex)
                </th>
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AN)
                </th>

                <th class="text-center">
                    @Html.DisplayNameFor(model => model.WardPre)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Opd)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                var classWardPre = Model.WardPre > 0 ? "btn-outline-warning" : "btn-light";
                var classOpd = Model.Opd > 0 ? "btn-outline-info" : "btn-light";
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.HN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FirstName)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => Model.LastName)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => Model.Birthdate)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => Model.Sex)
                    </td>
                    <td class="d-none d-md-table-cell">
                        @Html.DisplayFor(modelItem => Model.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.AN)
                    </td>

                    <td class="text-center">
                        @if (Model.WardPre == 0)
                        {
                            <a asp-controller="LogBook"
                               asp-action="Create_WardPre"
                               asp-route-an="@Model.AN"
                               class="btn @classWardPre btn-sm btn-block">
                                N/A
                            </a>

                        }
                        else
                        {
                            <a asp-controller="LogBook"
                               asp-action="Details_WardPre"
                               asp-route-an="@Model.AN"
                               class="btn @classWardPre btn-sm btn-block">
                                @Model.WardPre
                            </a>
                        }ZZ
                    </td>
                    <td class="text-center">
                        <a asp-controller="LogBook"
                           asp-action="Create_Opd"
                           asp-route-an="@Model.AN"
                           class="btn @classOpd btn-sm btn-block">
                            @(Model.Opd == 0 ? "N/A" : Model.Opd.ToString())
                        </a>
                    </td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>

</div>